/**
 * IntelHexParserTest.java
 * Copyright (c) 2016 DeNA Co., Ltd.
 *
 * This software is licensed under the GNU General Public License version 2.
 */
package com.dena.app.bootloadhid;

import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.InputStream;

import static org.junit.Assert.*;

public class IntelHexParserTest {

    private InputStream getResourceAsStream(String name) throws Exception {
        return this.getClass().getClassLoader().getResourceAsStream(name);
    }

    private byte[] getResourceAsBytes(String name) throws Exception {
        InputStream in = null;
        ByteArrayOutputStream out = null;
        try {
            in = getResourceAsStream(name);
            out = new ByteArrayOutputStream(in.available());
            byte[] buf = new byte[4096];
            while (true) {
                int len = in.read(buf, 0, buf.length);
                if (len < 0) {
                    break;
                }
                out.write(buf, 0, len);
            }
            in.close();
            return out.toByteArray();
        } finally {
            if (null != in) {
                in.close();
            }
            if (null != out) {
                out.close();
            }
        }
    }

    @Test
    public void testParseIntelHex() throws Exception {
        IntelHexParser hexData = new IntelHexParser();
        hexData.parseIntelHex(getResourceAsStream("miniBlink.ino.hex"));
        byte[] data = getResourceAsBytes("miniBlink.ino.bin");/* generated by 'hex2bin miniBlink.ino.hex' */
        assertArrayEquals(hexData.getData(), data);
    }

}
